# fly.toml app configuration file generated for frontend-quiet-moon-7365 on 2024-12-12T13:53:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pumahackernews'
primary_region = 'mad'

[build]
  builtin = "static"


[http_service]
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

